esphome:
  name: esphome-blink-offline
  # Подключаем ваш C++ файл
  includes:
    - blink_logic.h
  
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3

# Это аналог функции loop(), которая будет дергать твой C++ код
interval:
  - interval: 1s
    then:
      - lambda: 'my_blink();'
